const PREFIX = 'md-reader__'
const p = ([block]: TemplateStringsArray) => PREFIX + block

export default {
  PREFIX,
  MD_BODY: p`body`,
  MD_SIDE: p`side`,
  MD_SIDE_ACTIVE: p`side-li--active`,
  MD_CONTENT: p`markdown-content`,
  MD_BUTTON: p`btn`,
  HEAD_ANCHOR: p`head-anchor`,
  BUTTON_WRAP_ELE: p`button-wrap`,
  CODE_TOGGLE_BTN: p`btn--code-toggle`,
  SIDE_EXPAND_BTN: p`btn--side-expand`,
  GO_TOP_BTN: p`btn--go-top`,
  COPY_BTN: p`btn--copy`,
  SIDE_COLLAPSED: 'side-collapsed',
  SIDE_EXPANDED: 'side-expanded',
  MODAL: p`modal`,
  ZOOM_IMAGE: p`zoom-image`,
  SIDE_TABS: p`side-tabs`,
  SIDE_TAB_ITEM: p`side-tab-item`,
  SIDE_TAB_ITEM_ACTIVE: p`side-tab-item--active`,
  SIDE_PANEL: p`side-panel`,
  SIDE_PANEL_OUTLINE: p`side-panel--outline`,
  SIDE_PANEL_FOLDER: p`side-panel--folder`,
  FOLDER_WRAP: p`folder-wrap`,
  FOLDER_HEADER: p`folder-header`,
  FOLDER_SEARCH: p`folder-search`,
  FOLDER_TREE: p`folder-tree`,
  FOLDER_ITEM: p`folder-item`,
  FOLDER_ITEM_FILE: p`folder-item--file`,
  FOLDER_ITEM_DIR: p`folder-item--dir`,
  FOLDER_ITEM_ACTIVE: p`folder-item--active`,
  FOLDER_EMPTY: p`folder-empty`,
}
